executable              = sing.sh
arguments               = $(ClusterId)$(ProcId)
output                  = out/sing.$(ClusterId).$(ProcId).out
error                   = out/sing.$(ClusterId).$(ProcId).err
log                     = out/sing.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 2
request_CPUs = 2
+JobFlavour = "tomorrow"
+SingularityImage = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/library/centos:centos7"
queue
